import './globals.css'
import type { Metadata } from 'next'
import { Navbar } from './components'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<head>
				<link rel='stylesheet' href='https://use.typekit.net/sqg3ceb.css' />
			</head>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
